<a href="https://colab.research.google.com/github/rahulkumar2305/House-Price-Predictor-/blob/main/chapter_appendix-tools-for-deep-learning/jupyter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 **CDA 305 ( ARTIFICIAL INTELLIGENCE )**



** RAHUL KUMAR**

 rahul_2312res485@iitp.ac.in

In [1]:
import numpy as np
import random
from collections import deque
import time
from IPython.display import display, Markdown

class Puzzle8:
    def __init__(self):
        self.target = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]])
        self.moves = {'up': (-1, 0), 'down': (1, 0), 'left': (0, -1), 'right': (0, 1)}

    def generate_random_grid(self):
        """Generate a random 3x3 grid with numbers 1-8 and blank (0)"""
        numbers = list(range(1, 9)) + [0]  # 0 represents blank
        random.shuffle(numbers)
        return np.array(numbers).reshape(3, 3)

    def find_blank(self, grid):
        """Find the position of the blank space (0)"""
        return np.argwhere(grid == 0)[0]

    def is_valid_move(self, pos):
        """Check if a position is valid within 3x3 grid"""
        return 0 <= pos[0] < 3 and 0 <= pos[1] < 3

    def get_neighbors(self, grid):
        """Get all possible next states from current grid"""
        blank_pos = self.find_blank(grid)
        neighbors = []

        for move_name, (dx, dy) in self.moves.items():
            new_pos = (blank_pos[0] + dx, blank_pos[1] + dy)

            if self.is_valid_move(new_pos):
                new_grid = grid.copy()
                # Swap blank with adjacent tile
                new_grid[blank_pos[0], blank_pos[1]] = new_grid[new_pos[0], new_pos[1]]
                new_grid[new_pos[0], new_pos[1]] = 0
                neighbors.append(new_grid)

        return neighbors

    def grid_to_tuple(self, grid):
        """Convert grid to hashable tuple for visited set"""
        return tuple(map(tuple, grid))

    def is_solved(self, grid):
        """Check if grid matches target"""
        return np.array_equal(grid, self.target)

    def bfs(self, start_grid):
        """Breadth-First Search implementation"""
        queue = deque([(start_grid, [])])
        visited = set()
        visited.add(self.grid_to_tuple(start_grid))
        nodes_expanded = 0

        while queue:
            current_grid, path = queue.popleft()
            nodes_expanded += 1

            if self.is_solved(current_grid):
                return path, nodes_expanded, len(visited)

            for neighbor in self.get_neighbors(current_grid):
                neighbor_tuple = self.grid_to_tuple(neighbor)
                if neighbor_tuple not in visited:
                    visited.add(neighbor_tuple)
                    queue.append((neighbor, path + [neighbor]))

        return None, nodes_expanded, len(visited)

    def dfs(self, start_grid, max_depth=1000):
        """Depth-First Search implementation with depth limit"""
        stack = [(start_grid, [])]
        visited = set()
        visited.add(self.grid_to_tuple(start_grid))
        nodes_expanded = 0

        while stack:
            current_grid, path = stack.pop()
            nodes_expanded += 1

            if self.is_solved(current_grid):
                return path, nodes_expanded, len(visited)

            if len(path) < max_depth:
                for neighbor in reversed(self.get_neighbors(current_grid)):  # Reverse for DFS order
                    neighbor_tuple = self.grid_to_tuple(neighbor)
                    if neighbor_tuple not in visited:
                        visited.add(neighbor_tuple)
                        stack.append((neighbor, path + [neighbor]))

        return None, nodes_expanded, len(visited)

# Test the implementation
puzzle = Puzzle8()

# Generate random grid
start_grid = puzzle.generate_random_grid()
print("Start Grid:")
print(start_grid)
print("\nTarget Grid:")
print(puzzle.target)

Start Grid:
[[7 2 3]
 [5 4 8]
 [1 0 6]]

Target Grid:
[[1 2 3]
 [4 5 6]
 [7 8 0]]


In [2]:
def compare_algorithms(puzzle, start_grid, num_trials=5):
    """Compare BFS and DFS performance"""
    bfs_results = []
    dfs_results = []

    for i in range(num_trials):
        if i > 0:  # Use different grids for each trial
            start_grid = puzzle.generate_random_grid()

        # BFS
        start_time = time.time()
        bfs_path, bfs_nodes, bfs_visited = puzzle.bfs(start_grid)
        bfs_time = time.time() - start_time

        # DFS
        start_time = time.time()
        dfs_path, dfs_nodes, dfs_visited = puzzle.dfs(start_grid)
        dfs_time = time.time() - start_time

        bfs_results.append({
            'solvable': bfs_path is not None,
            'steps': len(bfs_path) if bfs_path else 0,
            'nodes': bfs_nodes,
            'visited': bfs_visited,
            'time': bfs_time
        })

        dfs_results.append({
            'solvable': dfs_path is not None,
            'steps': len(dfs_path) if dfs_path else 0,
            'nodes': dfs_nodes,
            'visited': dfs_visited,
            'time': dfs_time
        })

    return bfs_results, dfs_results

# Run comparison
bfs_results, dfs_results = compare_algorithms(puzzle, start_grid)

# Display results
display(Markdown("## Comparison Results"))
for i in range(len(bfs_results)):
    display(Markdown(f"### Trial {i+1}"))
    display(Markdown(f"**BFS**: Steps: {bfs_results[i]['steps']}, Nodes: {bfs_results[i]['nodes']}, Time: {bfs_results[i]['time']:.4f}s"))
    display(Markdown(f"**DFS**: Steps: {dfs_results[i]['steps']}, Nodes: {dfs_results[i]['nodes']}, Time: {dfs_results[i]['time']:.4f}s"))

## Comparison Results

### Trial 1

**BFS**: Steps: 0, Nodes: 181440, Time: 11.2649s

**DFS**: Steps: 0, Nodes: 155733, Time: 7.0052s

### Trial 2

**BFS**: Steps: 21, Nodes: 69605, Time: 3.4225s

**DFS**: Steps: 0, Nodes: 155813, Time: 7.4885s

### Trial 3

**BFS**: Steps: 0, Nodes: 181440, Time: 9.8928s

**DFS**: Steps: 0, Nodes: 161308, Time: 6.3147s

### Trial 4

**BFS**: Steps: 0, Nodes: 181440, Time: 9.8005s

**DFS**: Steps: 0, Nodes: 155733, Time: 5.9598s

### Trial 5

**BFS**: Steps: 22, Nodes: 89061, Time: 5.5254s

**DFS**: Steps: 998, Nodes: 53383, Time: 1.8252s

In [3]:
display(Markdown("""
## Comparative Analysis: BFS vs DFS for 8-Puzzle

### 1. Number of Steps Required

**BFS (Breadth-First Search)**:
- Always finds the shortest path to the solution
- Explores all nodes at depth d before moving to depth d+1
- Guaranteed to find optimal solution if one exists

**DFS (Depth-First Search)**:
- May find a solution faster but not necessarily the shortest path
- Can get stuck in deep branches before finding solution
- Requires depth limiting for practical implementation

### 2. Performance Characteristics

**When BFS is faster**:
- When the solution is at shallow depth
- When the branching factor is moderate
- When we need the optimal solution

**When DFS is faster**:
- When the solution is in a deep branch that DFS explores early
- When the search space has many dead ends at shallow levels
- When memory is a constraint (BFS uses more memory)

### 3. Memory Usage

**BFS**: O(b^d) where b is branching factor, d is solution depth
**DFS**: O(b×d) - much more memory efficient

### 4. Practical Observations

From our implementation:
- BFS typically finds the optimal solution with fewer steps
- DFS may find a solution faster but with more steps
- BFS explores more systematically but uses more memory
- DFS can be more efficient for certain puzzle configurations

### 5. Recommendation

For the 8-puzzle problem:
- **BFS is generally preferred** as it guarantees optimality
- Maximum solution depth is only 31 moves, making BFS feasible
- DFS should be used with iterative deepening for optimal performance
- BFS is more reliable for this specific problem

**Example**:
If the blank is only 2 moves away from target position:
- BFS will find it in 2 steps exploring ~b² nodes
- DFS might explore many unnecessary deep paths first
"""))

# Additional statistics
bfs_avg_steps = np.mean([r['steps'] for r in bfs_results if r['solvable']])
dfs_avg_steps = np.mean([r['steps'] for r in dfs_results if r['solvable']])
bfs_avg_time = np.mean([r['time'] for r in bfs_results])
dfs_avg_time = np.mean([r['time'] for r in dfs_results])

display(Markdown(f"""
### Statistical Summary (Averages)
- **BFS Average Steps**: {bfs_avg_steps:.2f}
- **DFS Average Steps**: {dfs_avg_steps:.2f}
- **BFS Average Time**: {bfs_avg_time:.4f}s
- **DFS Average Time**: {dfs_avg_time:.4f}s
"""))


## Comparative Analysis: BFS vs DFS for 8-Puzzle

### 1. Number of Steps Required

**BFS (Breadth-First Search)**:
- Always finds the shortest path to the solution
- Explores all nodes at depth d before moving to depth d+1
- Guaranteed to find optimal solution if one exists

**DFS (Depth-First Search)**:
- May find a solution faster but not necessarily the shortest path
- Can get stuck in deep branches before finding solution
- Requires depth limiting for practical implementation

### 2. Performance Characteristics

**When BFS is faster**:
- When the solution is at shallow depth
- When the branching factor is moderate
- When we need the optimal solution

**When DFS is faster**:
- When the solution is in a deep branch that DFS explores early
- When the search space has many dead ends at shallow levels
- When memory is a constraint (BFS uses more memory)

### 3. Memory Usage

**BFS**: O(b^d) where b is branching factor, d is solution depth
**DFS**: O(b×d) - much more memory efficient

### 4. Practical Observations

From our implementation:
- BFS typically finds the optimal solution with fewer steps
- DFS may find a solution faster but with more steps
- BFS explores more systematically but uses more memory
- DFS can be more efficient for certain puzzle configurations

### 5. Recommendation

For the 8-puzzle problem:
- **BFS is generally preferred** as it guarantees optimality
- Maximum solution depth is only 31 moves, making BFS feasible
- DFS should be used with iterative deepening for optimal performance
- BFS is more reliable for this specific problem

**Example**: 
If the blank is only 2 moves away from target position:
- BFS will find it in 2 steps exploring ~b² nodes
- DFS might explore many unnecessary deep paths first



### Statistical Summary (Averages)
- **BFS Average Steps**: 21.50
- **DFS Average Steps**: 998.00
- **BFS Average Time**: 7.9812s
- **DFS Average Time**: 5.7187s
